services:
  app:
    container_name: app_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres
      - nginx

  nginx:
    image: nginx:latest
    container_name: app_web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

  postgres:
    image: postgres:latest
    container_name: app_db
    restart: always
    ports:
      - "8200:5432"
    env_file:
      - .env
    volumes:
      - ./docker/volume/postgresql:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: app_adminer
    ports:
      - "8201:8080"
    depends_on:
      - postgres

  mailhog:
    image: mailhog/mailhog:latest
    container_name: app_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
