services:
  app:
    container_name: app_laravel
    restart: always
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres

  nginx:
    container_name: app_webserver
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  postgres:
    container_name: db_postgres
    image: postgres:latest
    restart: always
    ports:
      - "8200:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/volume/postgresql:/var/lib/postgresql/data

  adminer:
    container_name: db_adminer
    image: adminer
    ports:
      - "8201:8080"
    depends_on:
      - postgres

  mailhog:
    container_name: app_mail
    image: mailhog/mailhog:latest
    ports:
      - "8301:1025"
      - "8302:8025"
